#!/system/bin/sh

############################
# MtkTweak_V11 For MTK6577 #
#       作者:cx9208        #
#       -省电模式-         #
############################

LOG_FILE=/data/MtkTweak.log;
Mode=`cat /system/MtkTweakMode`;

if [ "$Mode" = "S" ]; then

if [ -e $LOG_FILE ]; then
	rm $LOG_FILE;
fi;

echo "MtkTweak优化脚本开始-时间： $( date +"%Y-%m-%d %H:%M:%S" )" | tee -a $LOG_FILE
echo "" | tee -a $LOG_FILE
echo "--> 优化模式：省电模式" | tee -a $LOG_FILE
echo "" | tee -a $LOG_FILE

#CPU调速器优化
echo "80" > /sys/devices/system/cpu/cpufreq/hybrid/up_threshold;
echo "60" > /sys/devices/system/cpu/cpufreq/hybrid/cpu_down_threshold;
echo "15" > /sys/devices/system/cpu/cpufreq/hybrid/down_differential;
echo "2" > /sys/devices/system/cpu/cpufreq/hybrid/sampling_down_factor;
echo "300" > /sys/devices/system/cpu/cpufreq/hybrid/cpu_down_avg_times;
echo "100" > /sys/devices/system/cpu/cpufreq/hybrid/cpu_up_bound;

#降低CPU最大频率1001Mhz-->951Mhz
echo "951000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;

#内核调整，CFS调整
sysctl -e -w kernel.panic=0;
sysctl -e -w kernel.random.write_wakeup_threshold=128;
sysctl -e -w kernel.random.read_wakeup_threshold=96;
sysctl -w kernel.threads-max=525810;
sysctl -w kernel.sched_child_runs_first=0;
sysctl -w kernel.sched_compat_yield=1;
sysctl -w kernel.sched_shares_ratelimit=256000;
echo "1000000" > /proc/sys/kernel/sched_min_granularity_ns;
echo "20000000" > /proc/sys/kernel/sched_latency_ns;
echo "2000000" > /proc/sys/kernel/sched_wakeup_granularity_ns;

#VM调整
sysctl -w vm.dirty_background_ratio=20;
sysctl -w vm.dirty_ratio=40;
sysctl -w vm.dirty_expire_centisecs=30000;
sysctl -w vm.dirty_writeback_centisecs=3000;
sysctl -w vm.min_free_kbytes=4096;
sysctl -w vm.vfs_cache_pressure=40;
sysctl -w vm.swappiness=0;
sysctl -w vm.page-cluster=0;
sysctl -w vm.min_free_order_shift=1;

fi