#!/system/bin/sh

############################
# MtkTweak_V12 For MTK6577 #
#       作者:cx9208        #
#  此脚本为共有的优化项目  #
############################

LOG_FILE=/data/MtkTweak.log

echo "--> 开始共有的优化" | tee -a $LOG_FILE
echo "" | tee -a $LOG_FILE

#IO、SD卡优化、修改默认调速器
tune2fs -o journal_data_writeback /block/path/to/system;
tune2fs -O ^has_journal /block/path/to/system;
tune2fs -o journal_data_writeback /block/path/to/cache;
tune2fs -O ^has_journal /block/path/to/cache;
tune2fs -o journal_data_writeback /block/path/to/data;
tune2fs -O ^has_journal /block/path/to/data;
DM=`ls -d /sys/block/dm-*`;
LOOP=`ls -d /sys/block/loop*`;
MMC=`ls -d /sys/block/mmc*`;
for i in $LOOP $MMC $DM;
do
    echo "0" > $i/queue/rotational;
	echo "0" > $i/queue/iostats;
    echo "384" > $i/queue/read_ahead_kb;
	echo "256" > $i/queue/nr_requests;
	echo "1" > $i/queue/nomerges;
done

echo "384" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;
echo "256" > /sys/devices/virtual/bdi/179:8/read_ahead_kb;
echo "256" > /sys/devices/virtual/bdi/179:32/read_ahead_kb;
echo "256" > /sys/devices/virtual/bdi/179:64/read_ahead_kb;
echo "256" > /sys/devices/virtual/bdi/179:96/read_ahead_kb;
echo "256" > /sys/devices/virtual/bdi/default/read_ahead_kb;
echo "128" > /sys/devices/virtual/bdi/7:0/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:1/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:2/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:3/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:4/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:5/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:6/read_ahead_kb；
echo "128" > /sys/devices/virtual/bdi/7:7/read_ahead_kb；
echo "97" > /sys/devices/virtual/bdi/179:0/max_ratio；
echo "97" > /sys/devices/virtual/bdi/default/max_ratio；
#chmod 777 /sys/block/mmcblk0/queue/scheduler
#echo "cfq" > /sys/block/mmcblk0/queue/scheduler
#chmod 777 /sys/block/mmcblk1/queue/scheduler
#echo "cfq" > /sys/block/mmcblk1/queue/scheduler
#chmod 777 /sys/block/mmcblk1/queue/scheduler
#echo "cfq" > /sys/block/mmcblk1/queue/scheduler

#IPV4优化、3G优化、防止SYN攻击
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout;
sysctl -e -w net.ipv4.tcp_congestion_control=cubic;
sysctl -e -w net.ipv4.conf.all.accept_redirects=0;
sysctl -e -w net.ipv4.conf.all.accept_source_route=0;
sysctl -e -w net.ipv4.conf.all.secure_redirects=0;
sysctl -e -w net.ipv4.conf.default.secure_redirects=0;
sysctl -e -w net.ipv4.conf.default.accept_source_route=0;
sysctl -e -w net.ipv4.conf.default.accept_redirects=0;
busybox sysctl -w net.core.wmem_max=1048576;
busybox sysctl -w net.core.rmem_max=1048576;
busybox sysctl -w net.core.optmem_max=20480;
busybox sysctl -w net.ipv4.tcp_moderate_rcvbuf=1;
busybox sysctl -w net.ipv4.route.flush=1;
busybox sysctl -w net.ipv4.udp_rmem_min=6144;
busybox sysctl -w net.ipv4.udp_wmem_min=6144;
busybox sysctl -w net.ipv4.tcp_rmem='6144 87380 1048576';
busybox sysctl -w net.ipv4.tcp_wmem='6144 87380 1048576';
setprop net.tcp.buffersize.default 4096,87380,256960,4096,16384,256960;
setprop net.tcp.buffersize.wifi 4096,87380,256960,4096,16384,256960;
setprop net.tcp.buffersize.umts 4096,87380,256960,4096,16384,256960;
setprop net.tcp.buffersize.edge 4096,87380,256960,4096,16384,256960;
setprop net.tcp.buffersize.gprs 4096,87380,256960,4096,16384,256960;
setprop ro.ril.hsxpa 0;
setprop ro.ril.hsupa.category 6;
setprop ro.ril.hsdpa.category 8;
setprop ro.ril.enable.dtm 1;
setprop ro.ril.enable.a53 1;
setprop ro.ril.enable.3g.prefix 1;
busybox sysctl -e -w net.ipv4.tcp_syncookies=1;
busybox sysctl -e -w net.ipv4.conf.all.rp_filter=1;
busybox sysctl -e -w net.ipv4.conf.default.rp_filter=1;
busybox sysctl -e -w net.ipv4.tcp_synack_retries=2;
busybox sysctl -e -w net.ipv4.tcp_syn_retries=2;
busybox sysctl -e -w net.ipv4.tcp_max_syn_backlog=1024;
busybox sysctl -e -w net.ipv4.tcp_max_tw_buckets=16384;
busybox sysctl -e -w net.ipv4.icmp_echo_ignore_all=1;
busybox sysctl -e -w net.ipv4.icmp_ignore_bogus_error_responses=1;
busybox sysctl -e -w net.ipv4.tcp_no_metrics_save=1;
busybox sysctl -e -w net.ipv4.tcp_fin_timeout=15;
busybox sysctl -e -w net.ipv4.tcp_keepalive_intvl=30;
busybox sysctl -e -w net.ipv4.tcp_keepalive_probes=5;
busybox sysctl -e -w net.ipv4.tcp_keepalive_time=1800;
busybox sysctl -e -w net.ipv4.ip_forward=0;

#dalvik虚拟机的Build调整
setprop dalvik.vm.execution-mode int:jit;
setprop dalvik.vm.checkjni false;
setprop dalvik.vm.dexopt-flags m=y;
setprop dalvik.vm.verify-bytecode ture;
setprop dalvik.vm.heapstartsize 8m;
setprop dalvik.vm.heapgrowthlimit 96m;
setprop dalvik.vm.heapsize 256m;

#改善MTK录像画质、音质
setprop ro.media.enc.hprof.vid.bps 3900000;
setprop ro.media.enc.mprof.vid.bps=1100000
setprop ro.media.enc.lprof.vid.bps=500000
setprop ro.media.enc.hprof.aud.hz 48000;
setprop ro.media.enc.mprof.aud.hz 16000;
setprop ro.media.enc.lprof.aud.hz 8000;
setprop ro.media.enc.hprof.aud.bps 96000;
setprop ro.media.enc.mprof.aud.bps 64000;
setprop ro.media.enc.lprof.aud.bps 32000
setprop ro.media.dec.jpeg.memcap 80000000;
setprop ro.media.enc.jpeg.quality 100;

#触摸、UI流畅性调整
setprop ro.min_pointer_dur 10
setprop video.accelerate.hw 1;
setprop debug.performance.tuning 1;
setprop windowsmgr.max_events_per_sec 150;
setprop debug.sf.hw 1;
setprop windowsmgr.support_rotation_270 true;
mount -t debugfs none /sys/kernel/debug;
echo NO_GENTLE_FAIR_SLEEPERS > /sys/kernel/debug/sched_features;

#zipalign对齐
ZIPALIGNDB=/data/MtkTweak_zipalign.db
APKDIR=/data/app

if [ ! -f $ZIPALIGNDB ]; then
    APKDIR=/system/app;
	touch $ZIPALIGNDB;
fi;

echo "全自动Zipalign开始 时间： $( date +" %H:%M:%S" )" | tee -a $LOG_FILE

for DIR in $APKDIR ; do
  cd $DIR
  for APK in *.apk ; do
    if [ $APK -ot $ZIPALIGNDB ] && [ $(grep "$DIR/$APK" $ZIPALIGNDB|wc -l) -gt 0 ] ; then
      echo "此APK已经zipalign过: $DIR/$APK" | tee -a $LOG_FILE
    else
      zipalign -c 4 $APK
      if [ $? -eq 0 ] ; then
        echo "此APK已经zipalign过: $DIR/$APK" | tee -a $LOG_FILE
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      else
        echo "开始处理: $DIR/$APK" | tee -a $LOG_FILE
        zipalign -f 4 $APK /cache/$APK
        busybox mount -o rw,remount /system
        cp -f -p /cache/$APK $APK
        busybox rm -f /cache/$APK
        grep "$DIR/$APK" $ZIPALIGNDB > /dev/null || echo $DIR/$APK >> $ZIPALIGNDB
      fi
    fi
  done
done

busybox mount -o ro,remount /system
touch $ZIPALIGNDB
echo "全自动Zipalign结束 时间： $( date +"%Y-%m-%d %H:%M:%S" )" | tee -a $LOG_FILE

#数据库优化
for i in \
`busybox find /data -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`busybox find /dbdata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

if [ -d "/datadata" ]; then
	for i in \
	`busybox find /datadata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

#清理垃圾、阻止垃圾生成
rm -r /data/local/tmp/*
rm -r /data/tmp/*
rm -r /data/system/usagestats/*
rm -r /data/system/appusagestats/*
rm -r /data/system/dropbox/*
rm -r /data/tombstones/*
rm -r /data/anr/*
busybox chmod 000 /data/system/userbehavior.db;
busybox chmod 000 /data/system/usagestats/;
busybox chmod 000 /data/system/dropbox/;
busybox chmod 000 /data/anr/;
busybox chmod 000 /data/tombstones/;
busybox chmod 000 /data/system/appusagestats/;
busybox chmod 000 /data/data/com.google.android.location/files/cache.cell;
busybox chmod 000 /data/data/com.google.android.location/files/cache.wif;

#电池寿命提升
rm /dev/log/events;
rm /dev/log/ksystem;
rm /dev/log/radio;
rm /dev/log/system;
rm /dev/log/main;
busybox mount -o remount,noatime,nodiratime,remount,rw,barrier=0,data=writeback /data;
busybox mount -o remount,noatime,nodiratime,remount,rw,barrier=0,data=writeback /cache;
busybox mount -o remount,noatime,nodiratime /dev;
busybox mount -o remount,noatime,nodiratime /proc;
busybox mount -o remount,noatime,nodiratime /sys;
busybox mount -o remount,noatime,nodiratime /system;
setprop ro.ril.disable.power.collapse 0;
setprop pm.sleep_mode 1;
setprop wifi.supplicant_scan_interval 270;
setprop status.battery.state Slow;
setprop status.battery.level 10;
setprop status.battery.level_raw 100;
setprop status.battery.level_scale 10;

#其他的调整
setprop ro.config.hwfeature_wakeupkey 1;
setprop persist.sys.use_dithering 1;
setprop mot.proximity.delay 250;
setprop persist.sys.purgeable_assets 1;
setprop ro.telephony.call_ring.delay 0;
setprop ro.ril.disable.power.collapse 1;
setprop persist.sys.shutdown.mode hibernate;
setprop ro.ext4fs 1;
setprop ro.config.hwfeature_wakeupkey 0;
setprop keyguard.no_require_sim true;
setprop ro.mot.eri.losalert.delay 000;
setprop ro.lge.proximity.delay 25;
setprop ro.HOME_APP_ADJ 1;

#暂停1分钟，等待系统载入完毕
sleep 60

#低内存杀手阈值调整
chmod 777 /sys/module/lowmemorykiller/parameters/adj;
chmod 777 /sys/module/lowmemorykiller/parameters/minfree;
echo "0,1,2,4,7,15" > /sys/module/lowmemorykiller/parameters/adj
echo "2048,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree;

#设置程序优先级
renice -20 `pidof com.android.phone`
renice -19 `pidof com.android.inputmethod.latin`
renice -19 `pidof com.swype.android.inputmethod`
renice -17 `pidof com.android.systemui`
renice -15 `pgrep android.process.acore`
renice -9 `pidof com.android.settings`
renice -9 `pidof com.android.vending`
renice -6 `pidof com.sec.android.app.camera`
renice -6 `pidof com.sec.android.app.fm`
renice -6 `pidof com.google.android.apps.maps`
renice -4 `pidof com.google.android.apps.googlevoice`
renice -3 `pidof android.process.media`

echo "--> 全部优化结束-时间： $( date +"%H:%M:%S" )" | tee -a $LOG_FILE

#版本：V12 全部完成！