#!/system/bin/sh

(
sleep 50

while true
do
cat /sys/power/wait_for_fb_sleep > /dev/null
sleep 1
echo 6 > /sys/power/cpufreq_limited_freq
cat /sys/power/wait_for_fb_wake > /dev/null
echo 0 > /sys/power/cpufreq_limited_freq
done
) &